MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: torchResNet.ResNet50_conv4_body
  FASTER_RCNN: True
NUM_GPUS: 1
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrain_imagenet_resnet50/model_best.pth.tar'
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 4000
  STEPS: [0, 1000, 2000, 3000]
RPN:
  SIZES: (8, 16, 32)
FAST_RCNN:
  ROI_BOX_HEAD: torchResNet.ResNet_roi_conv5_head
  QUERY_BOX_HEAD: torchResNet.ResNet_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  SCALES: (600,)
  MAX_SIZE: 1000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128
  CATEGORIES: [1]
TEST:
  SCALE: 600
  MAX_SIZE: 1000
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  CATEGORIES: [1]
