MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: torchResNet.ResNet50_conv4_body
  FASTER_RCNN: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrain_imagenet_resnet50/model_best.pth.tar'
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
FAST_RCNN:
  ROI_BOX_HEAD: torchResNet.ResNet_roi_conv5_head_co
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  SCALES: (600,)
  MAX_SIZE: 1000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 256
  CATEGORIES: [1]
TEST:
  SCALE: 600
  MAX_SIZE: 1000
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  CATEGORIES: [1]
